notaria/forms/login.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, NumberRange, ValidationError


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"%s - %s" %
                  (getattr(form, field).label.text, error), 'is-danger')


class loginForm(FlaskForm):
    user = StringField('Nombre de usuario', validators=[DataRequired()])
    passwd = PasswordField('Contraseña', validators=[DataRequired()])

notaria/blueprints/cert.py
from flask import Blueprint, render_template, session, redirect, url_for, flash

from notaria.blueprints.restrictions import login_required, login_restricted
from notaria.functions.wallet import get_keychain, get_unspent, create_tx
from notaria.functions.cert import process_file
from notaria.forms.cert import upload_form
from notaria.models.cert import cert_model
from sqlite3 import OperationalError

bp = Blueprint('cert', __name__, url_prefix='/cert')


@bp.route('/')
@login_required
def index():
    try:
        certs = cert_model.query.filter_by(username=session['user']).all()
    except OperationalError:
        certs = []
    return render_template('certs.html', certs=certs)


@bp.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():

    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    form = upload_form()

    if form.validate_on_submit():
        if process_file(session['user'], form):
            return redirect(url_for('cert.index'))
        else:
            flash("error al procesar el archivo")

    return render_template('upload.html', form=form, unspent=unspent)


@bp.route('/view/<string:sha3>')
@login_required
def view(sha3):
    flash(sha3)
    certs = cert_model.query.filter_by(username=session['user']).all()
    return render_template('certs.html', certs=certs)

notaria/blueprints/wallet.py
from flask import Blueprint, render_template, session, redirect, url_for, flash

from notaria.blueprints.restrictions import login_required, login_restricted
from notaria.functions.wallet import get_keychain, get_unspent, create_tx
from notaria.forms.wallet import send_form

bp = Blueprint('wallet', __name__, url_prefix='/wallet')


@bp.route('/')
@login_required
def index():
    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    return render_template('admin.html', address=address, unspent=unspent)


@bp.route("/send", methods=['GET', 'POST'])
@login_required
def send():
    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    form = send_form()
    if form.validate_on_submit():
        tx = create_tx(session['user'], form, 'hola')
        flash(tx)

    return render_template('send.html', form=form, unspent=unspent)

notaria/templates/nav/admin.html
<li><a href="{{ url_for('index.home') }}">Página principal<i class="material-icons">home</i></a></li>
<ul class="collapsible collapsible-accordion">
	<li><a class="collapsible-header">Wallet<i class="material-icons">account_balance_wallet</i></a>
		<div class="collapsible-body">
			<ul>
				<li><a href="{{ url_for('wallet.index') }}">Saldo</a></li>
				<li><a href="{{ url_for('wallet.send') }}">Transferir</a></li>
			</ul>
		</div>
	</li>
</ul>
<ul class="collapsible collapsible-accordion">
	<li><a class="collapsible-header">Certificados<i class="material-icons">assignment</i></a>
		<div class="collapsible-body">
			<ul>
				<li><a href="{{ url_for('cert.index') }}">Listado</a></li>
				<li><a href="{{ url_for('cert.upload') }}">Crear nuevo</a></li>
			</ul>
		</div>
	</li>
</ul>

notaria/templates/nav/login.html
<li><a href="{{ url_for('index.home') }}">Página principal<i class="material-icons">home</i></a></li>