notaria/models/cert.py
from notaria import db


class cert_model(db.Model):
    __tablename__ = 'certificados'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), unique=False, nullable=False)
    filename = db.Column(db.String(64), unique=True, nullable=False)
    size = db.Column(db.Integer, unique=False, nullable=False)
    sha3 = db.Column(db.String(64), unique=True, nullable=False)
    txid = db.Column(db.String(64), unique=True, nullable=False)

notaria/forms/cert.py
from flask_wtf.file import FileField, FileRequired
from flask_wtf import FlaskForm


class upload_form(FlaskForm):
    document = FileField('Subir archivo', validators=[FileRequired()])

notaria/forms/login.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, NumberRange, ValidationError


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"%s - %s" %
                  (getattr(form, field).label.text, error), 'is-danger')


class loginForm(FlaskForm):
    user = StringField('Nombre de usuario', validators=[DataRequired()])
    passwd = PasswordField('Contraseña', validators=[DataRequired()])

notaria/blueprints/cert.py
from flask import Blueprint, render_template, session, redirect, url_for, flash

from notaria.blueprints.restrictions import login_required, login_restricted
from notaria.functions.wallet import get_keychain, get_unspent, create_tx
from notaria.functions.cert import process_file
from notaria.forms.cert import upload_form
from notaria.models.cert import cert_model
from sqlite3 import OperationalError

bp = Blueprint('cert', __name__, url_prefix='/cert')


@bp.route('/')
@login_required
def index():
    try:
        certs = cert_model.query.filter_by(username=session['user']).all()
    except OperationalError:
        certs = []
    return render_template('certs.html', certs=certs)


@bp.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():

    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    form = upload_form()

    if form.validate_on_submit():
        if process_file(session['user'], form):
            return redirect(url_for('cert.index'))
        else:
            flash("error al procesar el archivo")

    return render_template('upload.html', form=form, unspent=unspent)


@bp.route('/view/<string:sha3>')
@login_required
def view(sha3):
    flash(sha3)
    certs = cert_model.query.filter_by(username=session['user']).all()
    return render_template('certs.html', certs=certs)

notaria/blueprints/wallet.py
from flask import Blueprint, render_template, session, redirect, url_for, flash

from notaria.blueprints.restrictions import login_required, login_restricted
from notaria.functions.wallet import get_keychain, get_unspent, create_tx
from notaria.forms.wallet import send_form

bp = Blueprint('wallet', __name__, url_prefix='/wallet')


@bp.route('/')
@login_required
def index():
    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    return render_template('admin.html', address=address, unspent=unspent)


@bp.route("/send", methods=['GET', 'POST'])
@login_required
def send():
    privkey, address = get_keychain(session['user'])
    unspent = get_unspent(address)

    form = send_form()
    if form.validate_on_submit():
        tx = create_tx(session['user'], form, 'hola')
        flash(tx)

    return render_template('send.html', form=form, unspent=unspent)

notaria/templates/admin.html
{% extends "base.html" %}
{% block body %}

<div class="center">
	<h2 class="title">Hola {{ session['user'] }} &#128516;</h2>

	<p class="mono">
		<img src="{{ qrcode(address, back_color='69F4BD', fill_color='444', border=2, box_size=9) }}">
		<br>
		{{ address }}
	</p>

	<p class="mono">{{ unspent['confirmed'] }} CHA</p>
</div>

{% endblock %}

{% block nav %}
{% include 'nav_admin.html' %}
{% endblock %}

notaria/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Control Panel</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons|Karla|Courier+Prime" rel="stylesheet">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<style type="text/css">
		body {font-family: 'Karla', sans-serif; display: flex; min-height: 100vh; flex-direction: column; }
		main { flex: 1 0 auto }
		header, main, footer { padding-left: 260px }
		@media only screen and (max-width : 992px) {header, main, footer { padding-left: 0} }
		input[type="text"]:not(.browser-default):focus:not([readonly]),
		input[type="password"]:not(.browser-default):focus:not([readonly]) { border-bottom: #6e6e6e; box-shadow: 0 1px 0 0 #6e6e6e; }
		input[type="text"]:not(.browser-default):focus:not([readonly]) + label,
		input[type="password"]:not(.browser-default):focus:not([readonly]) + label { color: #6e6e6e; }
		ul.sidenav.sidenav-fixed ul.collapsible-accordion a.collapsible-header{ padding:0 30px }
		.padding { padding-top: 3.6rem; }
		.color { background-color: #69F4BD; }
		.nav-bg { box-shadow: 0px 0px transparent; width: 260px; }
		.body-bg { background-color: #FEFEFE; }
		.mono { font-family: 'Courier Prime', monospace; }
		.btn:hover, .btn-large:hover, .btn-small:hover { background-color: transparent; }
		.title { text-transform: capitalize; }
		.toast { box-shadow: 0px 0px transparent; color: #222; }
		#toast-container {top: 5%; bottom: auto !important; }
	</style>
</head>
<body class="body-bg">
	<header>
		<div class="no-padding right">
			{% if session['user'] %}
			<a class="body-bg btn btn-flat white dropdown-trigger" href="/logout">Cerrar sesión</a>
			{% else %}
			<a class="body-bg btn btn-flat white dropdown-trigger" href="/login">Ingresar</a>
			<a class="body-bg btn btn-flat white dropdown-trigger" href="/register">Registrarse</a>
			{% endif %}
		</div>

		<div class="hide-on-large-only">
		<a href="#" data-target="nav-mobile" class="btn btn-flat btn-large sidenav-trigger"><i class="material-icons">menu</i></a>
		</div>

		<ul id="nav-mobile" class="sidenav sidenav-fixed nav-bg color padding">
			{% if session['user'] %}
				{% include 'nav/admin.html' %}
			{% else %}
				{% include 'nav/login.html' %}
			{% endif %}
	 	</ul>
	</header>

	<main>
		<div class="container section">
			{% block body %}
			{% endblock %}
		</div>
	</main>

	<footer class="page-footer white black-text">
		<div class="container center">
			Proyecto Chaucha
		</div>
	</footer>
            

	<script type="text/javascript">
	$( document ).ready(function() {
		$('.sidenav').sidenav();
		$('.collapsible').collapsible();
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				    M.toast({
				    	html: '{{ message }}',
				    	classes: 'toast color'
				});
				{% endfor %}
			{% endif %}
		{% endwith %}
	});
	</script>

</body>
</html>

notaria/templates/certs.html
{% extends "base.html" %}
{% block body %}

<h2 class="title">Certificados</h2>

<table>
	<thead>
		<tr>
			<th>nombre</th>
			<th>Tamaño</th>
			<th>Hash</th>
			<th>Certificado</th>
		</tr>
	</thead>
	<tbody>
	{% for cert in certs %}
	<tr>
		<td>{{cert.filename}}</td>
		<td>{{(cert.size/1024)|round(2) }} kb</td>
		<td class="mono">{{cert.sha3}}</td>
		<td><a href="{{ url_for('cert.view', sha3=cert.sha3) }}">ver más</a></td>
	</tr>
	{% endfor %}	
	</tbody>
</table>

{% endblock %}

notaria/templates/index.html
{% extends "base.html" %}
{% block body %}

<h2 class="title">{{ hello }} </h2>

<p>a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a </p>

{% endblock %}

notaria/templates/login.html
{% extends "base.html" %}
{% block body %}

<div class="row">
	<div class="col s12 l8 offset-l2">
		<div class="card">
			<div class="card-content">
				<span class="card-title center">Iniciar sesión</span>
				<div class="row">
					<form class="col s12" action="/login" method="POST">
						{{ form.csrf_token }}
						
						<div class="row">
							<div class="input-field col s12">
								{{ form.user }}
								{{ form.user.label }}
							</div>
							<div class="input-field col s12">
								{{ form.passwd }}
								{{ form.passwd.label }}
							</div>
						</div>
						<p>
							<button class="btn right white btn-flat" type="submit" name="action">
								<i class="material-icons">send</i>
							</button>
						</p>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

{% endblock %}

notaria/templates/register.html
{% extends "base.html" %}
{% block body %}

<div class="row">
	<div class="col s12 l8 offset-l2">
		<div class="card">
			<div class="card-content">
				<span class="card-title center">Registrar nuevo usuario</span>
				<div class="row">
					<form class="col s12" action="/register" method="POST">
						{{ form.csrf_token }}
						
						<div class="row">
							<div class="input-field col s12">
								{{ form.user }}
								{{ form.user.label }}
							</div>
							<div class="input-field col s12">
								{{ form.email }}
								{{ form.email.label }}
							</div>
							<div class="input-field col s12">
								{{ form.passwd }}
								{{ form.passwd.label }}
							</div>
						</div>
						<p>
							<button class="btn right white btn-flat" type="submit" name="action">
								<i class="material-icons">send</i>
							</button>
						</p>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

{% endblock %}

notaria/templates/send.html
{% extends "base.html" %}
{% block body %}

<div class="row">
	<div class="col l8 offset-l2">
		<h3 class="title">Transferir Chauchas</h3>
		<p><b>Saldo:</b> <span class="mono">{{ unspent['confirmed'] }} CHA</span></p>
		<div class="row">
			<form class="col s12" action="{{ url_for('wallet.send') }}" method="POST">
				{{ form.csrf_token }}
				
				<div class="row">
					<div class="input-field col s8">
						{{ form.address }}
						{{ form.address.label }}
					</div>
					<div class="input-field col s4">
						{{ form.amount }}
						{{ form.amount.label }}
					</div>
					<button class="btn right white btn-flat" type="submit" name="action">
						<i class="material-icons">send</i>
					</button>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

notaria/templates/upload.html
{% extends "base.html" %}
{% block body %}

<div class="row">
	<div class="col l8 offset-l2">
        <h3 class="title">Crear certificado</h3>
        <p>
            <b>Saldo:</b> <span class="mono">{{ unspent['confirmed'] }} CHA</span>
            <br>
            <b>Valor del certificado:</b> <span class="mono">1.00000000 CHA</span>
            <br>
            <b>Tamaño máximo:</b> 2 Mb</b>
        </p>
        <br>
		<div class="row">
			<form action="{{ url_for('cert.upload') }}" method="POST" enctype="multipart/form-data">
				{{ form.csrf_token }}
				
				<div class="row">
                    <div class="file-field input-field">
                        <div class="btn btn-flat color">
                            <span>{{ form.document.label.text }}</span>
                        </div>
                            {{ form.document }}
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
					<button class="btn right white btn-flat" type="submit" name="action">
						<i class="material-icons">send</i>
					</button>
				</div>
			</div>
        </div>
	</div>
</div>

{% endblock %}